import { describe, it, expect } from 'vitest'
import { existsSync, readFileSync } from 'node:fs'
import { derivePinyinInventory } from './lib/pinyin-inventory.mjs'

// Task 15 wrote the inventory deriver and the dual-backend build script but
// deliberately did not run synthesis, so public/data/pinyin.json and
// public/audio/pin/ do not exist yet -- see Task 16's amendment. Guard with
// skipIf rather than hardcoding a second copy of the expected-gap set: the
// moment a bank is built (via build-pinyin-audio.mjs), these assertions
// activate automatically, using derivePinyinInventory's own `unreachable`
// list as the expected-gap set. A red suite on a branch that is otherwise
// correct just teaches everyone to ignore red -- this test SKIPS, it never
// silently passes vacuous assertions against a bank that isn't there.
const MANIFEST_PATH = 'public/data/pinyin.json'
const hasManifest = existsSync(MANIFEST_PATH)

describe('mandarin audio coverage', () => {
  it.skipIf(!hasManifest)('has an mp3 for every derivable, reachable syllable', () => {
    const have = new Set(JSON.parse(readFileSync(MANIFEST_PATH, 'utf8')))
    const { syllables, unreachable } = derivePinyinInventory('public/data/dict.json')
    const unreachableSet = new Set(unreachable)

    // Unlike the Cantonese bank -- whose 14 gaps are inherited from an
    // upstream dataset we do not control -- this bank is generated by us
    // from a complete inventory. `unreachable` (syllables with no
    // single-character representative to hand a TTS frontend) is the ONLY
    // legitimate gap; anything else missing means the build genuinely
    // failed and re-running build-pinyin-audio.mjs is the fix. Do NOT add a
    // second, hardcoded gap list here -- it would drift from the deriver.
    const reachable = syllables.filter((s) => !unreachableSet.has(s))
    const missing = reachable.filter((s) => !have.has(s))
    expect(missing).toEqual([])

    // Guard the other direction too: if a syllable once thought unreachable
    // is now covered, the deriver's `unreachable` list is stale.
    expect(unreachable.filter((s) => have.has(s))).toEqual([])
  }, 120_000)

  it.skipIf(!hasManifest)('every audio file is named as a canonical pinyin syllable', () => {
    const have = JSON.parse(readFileSync(MANIFEST_PATH, 'utf8'))
    expect(have.filter((s) => !/^[a-z]+[0-4]$/.test(s))).toEqual([])
  })

  if (!hasManifest) {
    it('SKIPPED: no Mandarin audio bank has been built yet (public/data/pinyin.json is absent)', () => {
      expect(hasManifest).toBe(false)
    })
  }
})
